# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: Azure App Service - firstwapptest(Production), Build and deploy ASP .NET app

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master


    - name: Setup MSBuild path
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      - name: Publish NuGet packages
  # You may pin to the exact commit or the version.
  # uses: dansiegel/publish-nuget@d6dfbff478dcf0bb623fecad3b2a1ee1c4fd25cb
  uses: dansiegel/publish-nuget@v1.01
  with:
    # NuGet package filename or search pattern
    filename: # default is **/*.nupkg
    # API key to access the feed
    apiKey: 
    # NuGet feed URL
    feedUrl: # optional, default is https://api.nuget.org/v3/index.json

    - name: Restore NuGet packages
      run: nuget restore

    - name: Publish to folder
      run: msbuild /nologo /verbosity:m /t:Build /t:pipelinePreDeployCopyAllFilesToOneFolder /p:_PackageTempDir="\published\"

    - name: Run Azure webapp deploy action using publish profile credentials
      uses: azure/webapps-deploy@v2
      with:
        app-name: firstwapptest
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_A3F9B18BD0504C9797B21EA8D853164D }}
        package: \published\

